"""empty message

Revision ID: 4c7d1daaf9da
Revises: a5cffa318ac2
Create Date: 2024-08-21 11:19:20.957708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7d1daaf9da'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=False),
    sa.Column('hair_color', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personajes_relacion', sa.Integer(), nullable=False),
    sa.Column('usuarios_relacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_relacion'], ['personajes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuarios_relacion'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planetas_relacion', sa.Integer(), nullable=False),
    sa.Column('usuarios_relacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planetas_relacion'], ['planetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuarios_relacion'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculos_relacion', sa.Integer(), nullable=False),
    sa.Column('usuarios_relacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuarios_relacion'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehiculos_relacion'], ['vehiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('favoritos_vehiculos')
    op.drop_table('favoritos_planetas')
    op.drop_table('favoritos_personajes')
    op.drop_table('vehiculos')
    op.drop_table('users')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
